const implementacion = import.meta.env.VITE_API_MODE === 'real'
  ? await import('./ServerConnection/index.js')
  : await import('./LocalAPI/index.js');

export const {
  listarCatalogos,
  listarSesiones,
  crearSesiones,
  celebrarSesion,
  comenzarSesion,
  editarHorario,
  listarAsistencia,
  registrarAsistencia,
  listarFechasExtraordinaria,
  crearSesionExtraordinaria,
  eliminarSesion,
  establecerListaCerrada,
  obtenerCalendario,
  generarCalendarioAnual,
  resumenArchivoCalendario,
  listarGeneraciones,
  agregarAsueto,
  quitarAsueto,
  listarPuntos,
  crearPunto,
  editarPunto,
  eliminarPunto,
  reordenarPuntos,
  marcarPunto,
  marcarPuntos,
  enviarEngrose,
  registrarVotacion,
  listarIntegrantes,
  crearIntegrante,
  editarIntegrante,
  eliminarIntegrante,
  obtenerSecretarioEjecutivo,
  guardarSecretarioEjecutivo,
  eliminarSecretarioEjecutivo,
  adjuntarArchivos,
  eliminarArchivo,
  descargarArchivo,
  listarContactosCorreo,
  crearContactoCorreo,
  eliminarContactoCorreo,
  listarPlantillasCorreo,
  crearPlantillaCorreo,
  eliminarPlantillaCorreo,
  listarListasCorreo,
  crearListaCorreo,
  eliminarListaCorreo,
  listarCorreosRemitentes,
  guardarCorreoRemitente,
  listarCorreosEnviados,
  enviarCorreo,
} = implementacion;
